### ISSUE TITLE
fehlerhaft formatierter Vereinsname  Hamburger SV

### ISSUE THREAD

**Issue by thilopohl** [Deutscher-Leichtathletikverband/Stammdatenaustausch#130]
Hallo zusammen, 
bei den Meldebearbeitung zu den Deutschen Meisterschaften ist aufgefallen, dass der Verein 
"HH0001113 Hamburger SV"  falsch geschrieben ist.

Auf den Vereinsnamen nach dem SV folgt noch ein Leerzeichen:

Ausschnitt als CSV-Datei
```
;Hamburger SV ;HH0001113;GER;HH;
;Hamburger SV ;HH0001113;GER;HH;
;Hamburger SV ;HH0001113;GER;HH;
```
Wer kümmernt sich wohl drum? 
Danke+VG
Thilo

**Comment by mschunk** [comment]
@thilopohl ich wollte gerade schreiben "ich kümmere mich drum", habe dann aber mal nachgesehen. Bei dem `Hamburger SV` gibt es kein Leerzeichen am Ende vom Namen. Weder in den Stammdaten in LADV noch in der Meldungen-XML.

Woher kommt denn diese CSV-Datei?

**Comment by thilopohl** [comment]
Quelle war ggf. der Startrechts Stammdatenimport der "Definitionen" in taf3, nach einer manuellen Zuordnung der Deutschen Athleten-ID (GUID) nach dem Einlesen der Meldungen aus den LADV Daten (....-Meldungen-0.7.xml)

Leider kann ich das in einer neu angelegten sauberen Datenbank jetzt nicht mehr nachstellen oder reproduzieren. Vermutlich doch ein Flüchtigkeitsfehler auf meiner Seite. Geschlossen. Sorry.
