### ISSUE TITLE
Phönix: Probleme mit Gemeinschaften

### ISSUE THREAD

**Issue by mschunk** [Deutscher-Leichtathletikverband/Stammdatenaustausch#61]
Landesverbände die Phönix nutzen haben Probleme Änderungen bei Gemeinschaften korrekt bereitzustellen. Es gibt in diesem Umfeld Diverse Probleme, hier nur mal zwei Beispiel, für weitere Details bitte direkt mit den Landesverbänden (Württemberg, Niedersachsen und Sachsen) sprechen.

### Problem 1: Änderung Altersklassen einer STG.
Eine STG hat zwei Mitgliedsvereine. 2019 gilt die STG für die Altersklassen Jugend U16/U14 M. Ab 2020 kommt U16/U14 W dazu.
In der XML hätte ich folgendes erwartet:
```xml
<Club ID="SN0002051" Type="STG" Name="StG ..." ClubDateStart="2019-01-01" ...>
  <MemberClubs>
    <MemberClub ID="..." Name="Verein A" MemberDateStart="2019-01-01" 
MemberDateEnd="2019-12-31" MemberAgeGroups="U16U14M"/>
    <MemberClub ID="..." Name="Verein B" MemberDateStart="2019-01-01" 
MemberDateEnd="2019-12-31" MemberAgeGroups="U16U14M"/>
    <MemberClub ID="..." Name="Verein A" MemberDateStart="2020-01-01" 
MemberDateEnd="2020-12-31" MemberAgeGroups="U16U14W U16U14M"/>
    <MemberClub ID="..." Name="Verein B" MemberDateStart="2020-01-01"
MemberDateEnd="2020-12-31" MemberAgeGroups="U16U14W U16U14M"/>
  </MemberClubs>
</Club>
```

Was ich derzeit erhalte ist:
```xml
<Club ID="SN0002051" Type="STG" Name="StG ..." ClubDateStart="2019-01-01" ...>
  <MemberClubs>
    <MemberClub ID="..." Name="Verein A" MemberDateStart="2019-01-01"
MemberAgeGroups="U16U14W U16U14M"/>
    <MemberClub ID="..." Name="Verein B" MemberDateStart="2019-01-01"
MemberAgeGroups="U16U14W U16U14M"/>
  </MemberClubs>
</Club>
```

### Problem 2: Änderung Mitgliedsvereine einer STG.
Eine STG hat drei Mitgliedsvereine in 2019 (Verein A/Verein B/Verein C). 2020 tritt Verein C aus und Verein D zu.

In der XML hätte ich folgendes erwartet:
```xml
<Club ID="SN0002051" Type="STG" Name="StG ..." ClubDateStart="2019-01-01" ...>
  <MemberClubs>
    <MemberClub Name="Verein A" MemberDateStart="2019-01-01" MemberAgeGroups="U16U14W"/>
    <MemberClub Name="Verein B" MemberDateStart="2019-01-01" MemberAgeGroups="U16U14W"/>
    <MemberClub Name="Verein C" MemberDateStart="2019-01-01" MemberDateEnd="2019-12-31" MemberAgeGroups="U16U14W"/>
    <MemberClub Name="Verein D" MemberDateStart="2020-01-01" MemberAgeGroups="U16U14W"/>
  </MemberClubs>
</Club>
```

Was ich derzeit erhalte (Verein C ist verschwunden):
```xml
<Club ID="SN0002051" Type="STG" Name="StG ..." ClubDateStart="2019-01-01" ...>
  <MemberClubs>
    <MemberClub Name="Verein A" MemberDateStart="2019-01-01" MemberAgeGroups="U16U14W"/>
    <MemberClub Name="Verein B" MemberDateStart="2019-01-01" MemberAgeGroups="U16U14W"/>
    <MemberClub Name="Verein D" MemberDateStart="2020-01-01" MemberAgeGroups="U16U14W"/>
  </MemberClubs>
</Club>
```

Bitte mit den Landesverbänden klären wie die Gemeinschaften korrekt zu erfassen sind.

**Comment by mschunk** [comment]
@santwer gibt es hier ein update?

**Comment by santwer** [comment]
Wir haben alle Anpassungen in diesem Bezug durchgeführt und eingespielt. Da beim durchführen der Änderungen keine Historie für die Altersklassen der StGs verfügbar waren, werden diese Altersgruppen nun nicht übertragen. Da die Altersklassen bei einem MemberClub nicht fehlen dürfen, siehe #47, können wir die Vereine dessen Altersklassen sich geändert haben nicht mit übertragen.

Somit können die Daten von StGs nicht wie hier beschrieben erwartet übertragen werden. Es ist ein großer Aufwand diese Änderungen nachträglich bei den Verbänden abzufragen und diese händisch einzutragen.

**Comment by mschunk** [comment]
> Somit können die Daten von StGs nicht wie hier beschrieben erwartet übertragen werden. Es ist ein großer Aufwand diese Änderungen nachträglich bei den Verbänden abzufragen und diese händisch einzutragen.

Das was hier beschrieben ist, ist was die Schnittstellenbeschreibung aussagt. Die zusammenfassung davon ist: Phönix ist nicht in der Lage Startgemeinschaften Schnittstellenkonform bereitzustellen.

Wenn sich die aus Phönix bereitgestellten Daten nicht an die Schnittstellenbeschreibung halten, kann LADV die Daten nicht einlesen - Datenübernahme nach LADV ist nicht möglich.
