### ISSUE TITLE
Vereine die keine Vereine sind

### ISSUE THREAD

**Issue by mschunk** [Deutscher-Leichtathletikverband/Stammdatenaustausch#83]
Im LV Westfalen erhalten wir eine Reiehe Vereine die keine Vereine sind. Beispiele:
```
3944: CONTACT GmbH
3935: DLM GmbH
3946: upletics GmbH
3906: Paderborner Osterlauf GmbH

3930: Stadtsportbund Hamm
3931: Stadt Hamm
3932: Stadt Dortmund 
```

Thilo Phol hat diese Vereine so erklärt:
> Die ‚Vereine‘ werden gebraucht, für die Anmeldung der Stadionfernen Läufe. Diese sind genauso auch in DLVnet Admin enthalten. Startpässe/Athleten haben die nicht . Also könnten sie Z.B. nur manuell Melden in LADV. Es ist jetzt schon so, dass sie sich eine Seltec Lizenz ziehen könnten. Unter Service.laportal.net. Das kann aber sogar gewünscht sein, da sie ja Ausrichter sind.

Ich verstehe warum diese "nicht Vereine" bereitgestellt/übertragen werden. Trotzdem sind es keine Vereine die für Meldungen verwendet werden dürfen. Im Moment gibt es keine Möglichkeit diese "nicht Vereine" (oder sollten wir Verbandsfremde Organisationen dazu sagen?) zu identifizieren.

Lösungsvorschlag: Das Attribut Type im Element Club hat derzeit drei mögliche Werte: `Club|LG|STG`. Es wäre kein Problem hier einen weiteren Wert zuzulassen - beispielsweise `ORGANISATION`. Diese können dann übertragen werden wenn dies gewünscht ist. Ein System das diese Daten erhält kann nun erkennen, dass es sich um keine "echten Vereine" handelt und entsprechend reagieren (Organisationen nicht für Online Meldungen zulassen).

Die Erweiterung des CLUB.XSD wäre ein none-breaking change. Alle bisherigen Dateien wären weiterhin gültig.

**Comment by santwer** [comment]
Ich finde den Lösungsvorschlag angebracht. Wir würden die Daten von nicht Vereinen eigentlich nicht übernehmen, könnten diese durch einen Type filtern. 
Aktuell würden wir die Organisationen übernehmen und später über einen Abgleich löschen.

**Comment by diwaffm** [comment]
Ein "Nicht-Verein" ist im Moment in LA.Net nicht vorgesehen...

**Comment by mschunk** [comment]
Auch in Nordhrein erhalten wir aus la.net eine Reihe Vereine die m.eE. keine Vereine sind:
```
1575: LVN Geschäftsstelle
99028: SportScheck
99031: Golazo Sports GmbH
99032: AG Apfelblütenlauf
99033: Ausschuss für den Schulsport
99035: CONTACT GmbH
99036: Welthungerhilfe e.V.
99037: SV 1923 Kalterherberg e.V.
99038: Fachschaft LA im SSB Wuppertal
99039: Deutschland Läuft GmbH
```

**Comment by thilopohl** [comment]
Für Westfalen hat übrigens die Bereinigung stattgefunden. Alle Vereinsnummern beginnen mit 39xx wurden im Mastersystem Lanet2 auf ORG umgeschlüsselt.

**Comment by mschunk** [comment]
Die ORGs werden über den Stammdatenaustausch auch bereitgestellt. Damit ist dieses Issue m.E. erledigt.
