### ISSUE TITLE
Pfalz: Diverse Datenprobleme Athleten

### ISSUE THREAD

**Issue by mschunk** [Deutscher-Leichtathletikverband/Stammdatenaustausch#96]
Datenabruf: 02.06.2020
Datenart: full

Die Athletendaten der Pfaz weisen mehrere Probleme auf.

Es gibt in den Daten eine Reihe Athleten die ein aktives Startrecht für einen nicht existenten Verein besitzen. Beispiel:
```xml
<Person PersonID="c3450b08-fbfc-11e9-bde2-6c626d40fea8" FirstName="Jonas" LastName="B." ClubID="PF0000522" ...>
<Licenses>
<License LicenseNumber="PF0081734" HomeClubID="PF0000522" LicenseClubID="PF0000522" LicenseStart="2009-01-21" LastUpdated="2011-12-20 10:23:08"/>
```

Ein Verein mit der ClubID `PF0000522` existiert nicht.

Weitere Betroffene Athleten:
```
c344ff4e-fbfc-11e9-bde2-6c626d40fea8
c6ef9f8a-fbfc-11e9-bde2-6c626d40fea8
c344fdbd-fbfc-11e9-bde2-6c626d40fea8
c7cdbacb-fbfc-11e9-bde2-6c626d40fea8
c7d50544-fbfc-11e9-bde2-6c626d40fea8
c344f371-fbfc-11e9-bde2-6c626d40fea8
c344f4d5-fbfc-11e9-bde2-6c626d40fea8
c5ed8b7a-fbfc-11e9-bde2-6c626d40fea8
c344f623-fbfc-11e9-bde2-6c626d40fea8
c33abf6d-fbfc-11e9-bde2-6c626d40fea8
c33ac2fc-fbfc-11e9-bde2-6c626d40fea8
c345099f-fbfc-11e9-bde2-6c626d40fea8
c3450c52-fbfc-11e9-bde2-6c626d40fea8
c3450592-fbfc-11e9-bde2-6c626d40fea8
c7b0c877-fbfc-11e9-bde2-6c626d40fea8
c345044e-fbfc-11e9-bde2-6c626d40fea8
c34502f8-fbfc-11e9-bde2-6c626d40fea8
c344fb1d-fbfc-11e9-bde2-6c626d40fea8
c344f779-fbfc-11e9-bde2-6c626d40fea8
```

Desweiteren gibt es Athleten mit mehreren gültigen überlappenden Lizenzen. Beispiel:
```xml
<Person PersonID="81E9999A-FEEA-41E2-B47A-68E1EEBB6B0E" FirstName="Joel" LastName="V.">
<Licenses>
<License LicenseNumber="PF0982719" HomeClubID="PF0000023" LicenseClubID="PF0000023" LicenseStart="2020-03-17" LastUpdated="2020-03-17 08:07:56"/>
<License LicenseNumber="PF0982719" HomeClubID="PF0000023" LicenseClubID="PF0000023" LicenseStart="2020-03-29" LastUpdated="2020-03-29 10:31:06"/>
```

Mehrfach vergebene Startrechtnummer. Beispiel `PF0081441`:
```xml
<Person PersonID="c33c5c52-fbfc-11e9-bde2-6c626d40fea8" FirstName="Michelle" LastName="M." ...>
<Licenses>
<License LicenseNumber="PF0081441" HomeClubID="PF0000234" LicenseClubID="PF0000234" LicenseStart="2009-10-17" LastUpdated="2011-12-20 10:23:08"/>

<Person PersonID="c341be21-fbfc-11e9-bde2-6c626d40fea8" FirstName="Martin" LastName="D." ...>
<Licenses>
<License LicenseNumber="PF0081441" HomeClubID="PF0000278" LicenseClubID="PF0000278" LicenseStart="2008-02-07" LastUpdated="2011-12-20 10:23:08"/>
```

Athlet jünger als drei Jahre (i.d.R. falsch erfasstes Geburtsdatum): `c7fb6e72-fbfc-11e9-bde2-6c626d40fea8`

**Comment by diwaffm** [comment]
Die geschilderten Probleme sind nach Aussage des LV Pfalz beseitigt

**Comment by mschunk** [comment]
Datenabruf 16.06.2020 22:37 Uhr. Probleme sind weiterhin vorhanden.

**Comment by diwaffm** [comment]
Ja, weil Du vor der Erstellung der Datei mit dem neuen Datenbestand drauf zugegriffen hat (müsste Stand 16.6. gewesen sein). 

In der Datei, die am 17.6. um 00:04 erstellt wurde, sind die Fehler nicht mehr vorhanden...

**Comment by mschunk** [comment]
Datenabruf am 19.06.2020 22:06 Uhr.

> In der Datei, die am 17.6. um 00:04 erstellt wurde, sind die Fehler nicht mehr vorhanden...

Nicht wirklich. Es sind weiterhin 7 Athleten entahlten die ein aktives Startrecht für nicht existene Vereine haben:
```
Startpassnummer: '982206' / 'c6ef9f8a-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '982219' / 'c7cdbacb-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '982262' / 'c7d50544-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '510238' / 'c5ed8b7a-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '63400' / 'c33abf6d-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '63430' / 'c33ac2fc-fbfc-11e9-bde2-6c626d40fea8'
Startpassnummer: '982001' / 'c7b0c877-fbfc-11e9-bde2-6c626d40fea8'
```

> Ja, weil Du vor der Erstellung der Datei mit dem neuen Datenbestand drauf zugegriffen hat (müsste Stand 16.6. gewesen sein).

Oh das hattest du garnicht erwähnt.

**Comment by diwaffm** [comment]
Die Athleten wurden überprüft und korrekt zugeordnet...

Neue Austauschdatei wurde am 26.6., 14:01 erstellt.

**Comment by mschunk** [comment]
Datenabruf am 16.07. - keine weiteren Datenprobleme
