### ISSUE TITLE
Datenabruf von LADV nicht möglich

### ISSUE THREAD

**Issue by diwaffm** [Deutscher-Leichtathletikverband/Stammdatenaustausch#98]
Der Aufruf von _https://ladv.de/dlvApi/clubs?stateId=BA_ (wobei die StateId egal ist) bringt zur Zeit nur ein
`https required`

Die Response header lauten
```
server: nginx
date: Fri, 26 Jun 2020 12:12:05 GMT
content-type: text/html;charset=utf-8
transfer-encoding: chunked
connection: keep-alive
set-cookie: JSESSIONID=7EC6655FF51A1B963BB7A478EF1E70C0.ladv; Path=/; HttpOnly
```

**Comment by mschunk** [comment]
Das Problem wurde heute ca. 15 Uhr behoben. 

Danke für den Hinweis.
