### ISSUE TITLE
LV Hessen: Athleten fehlen

### ISSUE THREAD

**Issue by mschunk** [Deutscher-Leichtathletikverband/Stammdatenaustausch#99]
Der ASC Darmstadt möchte zwei Athleten über LADV melden die ein aktives Startrecht haben:
1913589 Furtwängler, C.
1917969 Graffe, S.

Sabrina Müller vom HLV hat bestätigt das die Athleten in Phönix korrekt angelegt sind und ein aktives Startrecht besitzen. In der Athletendat für den LV Hessen, sind die beiden genannten Athleten / Startrechtnummern nicht vorhanden (Stand 02.07.2020 2 Uhr). Offensichtlich fehlen die beiden Athleten in der Bereitstellung aus Phönix.

Die Datei die wir heute abgerufen haben sinde ich via Email.

**Comment by TobyMaxham** [comment]
Hallo @mschunk,

die Athleten werden im Datenaustausch nun wieder mit aufgeführt.
Diese wurden nicht korrekt in PhoenixII erfasst. Details dazu sende ich per E-Mail.

Mit freundlichen Grüßen
Tobias Maxham

**Comment by mschunk** [comment]
Die als fehlend gemeldeten Athleten sind nun vorhanden.
